# Generated by Django 5.2.3 on 2025-06-23 19:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(max_length=5)),
                ('documento', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('producto', models.CharField(max_length=10)),
                ('poliza', models.CharField(max_length=50)),
                ('periodo', models.CharField(max_length=1)),
                ('valor_asegurado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_prima', models.DecimalField(decimal_places=2, max_digits=12)),
                ('doc_cobro', models.CharField(max_length=20)),
                ('fecha_ini', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('dias', models.IntegerField()),
                ('telefono_1', models.CharField(blank=True, max_length=15)),
                ('telefono_2', models.CharField(blank=True, max_length=15)),
                ('telefono_3', models.CharField(blank=True, max_length=15)),
                ('ciudad', models.CharField(max_length=50)),
                ('departamento', models.CharField(max_length=50)),
                ('fecha_venta', models.DateField()),
                ('fecha_nacimiento', models.DateField()),
                ('tipo_trans', models.CharField(max_length=3)),
                ('beneficiarios', models.TextField(blank=True)),
                ('genero', models.CharField(max_length=1)),
                ('sucursal', models.CharField(max_length=100)),
                ('tipo_cuenta', models.CharField(blank=True, max_length=20)),
                ('ultimos_digitos_cuenta', models.CharField(blank=True, max_length=10)),
                ('entidad_bancaria', models.CharField(max_length=100)),
                ('nombre_banco', models.CharField(max_length=100)),
                ('estado_debito', models.CharField(max_length=20)),
                ('causal_rechazo', models.CharField(blank=True, max_length=255)),
                ('codigo_canal', models.CharField(max_length=3)),
                ('descripcion_canal', models.CharField(max_length=255)),
                ('codigo_estrategia', models.CharField(max_length=50)),
                ('tipo_estrategia', models.CharField(max_length=100)),
                ('correo_electronico', models.EmailField(blank=True, max_length=254)),
                ('fecha_entrega_colmena', models.DateField(default=django.utils.timezone.now)),
                ('mes_a_trabajar', models.IntegerField(default=6)),
                ('nombre_db', models.CharField(max_length=255)),
                ('texto', models.BooleanField(default=False)),
                ('email', models.BooleanField(default=False)),
                ('telefono', models.BooleanField(default=False)),
                ('whatsapp', models.BooleanField(default=False)),
                ('fisica', models.BooleanField(default=False)),
                ('mejor_canal', models.CharField(blank=True, max_length=20)),
                ('contactar_al', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'registro',
            },
        ),
    ]
