# Generated by Django 5.2.3 on 2025-06-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0002_alter_registro_fecha_ini_alter_registro_telefono_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='documento',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
