# Generated by Django 5.2.3 on 2025-06-24 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0003_alter_registro_documento_alter_registro_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='dias',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='fecha_venta',
            field=models.DateField(blank=True, null=True),
        ),
    ]
