# Generated by Django 5.2.3 on 2025-06-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0004_alter_registro_dias_alter_registro_fecha_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
